# Generated by Django 5.1.15 on 2026-02-06 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("json_schema", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("number", "Number Input"),
                            ("textarea", "Textarea"),
                            ("dropdown", "Dropdown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=1)),
                ("required", models.BooleanField(default=False)),
                ("help_text", models.CharField(blank=True, max_length=512)),
                ("placeholder", models.CharField(blank=True, max_length=255)),
                ("default_value", models.CharField(blank=True, max_length=255)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "custom_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="formbuilder.customform",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("custom_form", "slug"), name="unique_field_slug_per_form"
                    ),
                    models.UniqueConstraint(
                        fields=("custom_form", "position"), name="unique_field_position_per_form"
                    ),
                ],
            },
        ),
    ]
