# Generated by Django 5.1.15 on 2026-02-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formbuilder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Input"),
                    ("number", "Number Input"),
                    ("textarea", "Textarea"),
                    ("dropdown", "Dropdown"),
                    ("radio", "Radio Buttons"),
                    ("checkbox", "Checkboxes"),
                    ("rating", "Rating Scale"),
                    ("boolean", "Yes/No"),
                    ("email", "Email Address"),
                    ("date", "Date Picker"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FieldOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField(default=1)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="formbuilder.formfield",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("field", "value"), name="unique_option_value_per_field"
                    ),
                    models.UniqueConstraint(
                        fields=("field", "position"), name="unique_option_position_per_field"
                    ),
                ],
            },
        ),
    ]
