# Generated by Django 5.1.15 on 2026-02-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formbuilder", "0002_alter_formfield_field_type_fieldoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="question",
            field=models.TextField(
                blank=True, help_text="Detailed question or explanation shown to users"
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="label",
            field=models.CharField(help_text="Short field label shown in forms", max_length=255),
        ),
    ]
